### ISSUE TITLE
mapa mental de conjuntos y relaciones 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/mapa-mental-saul19bautista#2]
[MAPA MENTAL DE CONJUNTOS Y RELACIONES.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-saul19bautista/files/7272734/MAPA.MENTAL.DE.CONJUNTOS.Y.RELACIONES.pdf)

**Comment by 71santiago7** [comment]
20%
EXCELENTE  TRABAJO

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
